variables:
    VPC_NAME:
        required: true
        description: the name of the VPC
        default: my-subnet
    PUBLIC_SUBNET_NAME:
        required: true
        description: the cloudcoreo name of the public vpc subnets
        default: my-public-subnet
    VPC_OCTETS:
        required: true
        description: the octets for the vpc ip range - i.e. xxx.xxx.xxx.xxx
        default: 10.0.0.0
    PUBLIC_ROUTE_NAME:
        required: true
        description: the name to give to the public route
        default: my-public-route